version: '3'

services:
  ghost:
    image: ghost:3.2.0
    container_name: ghost
    volumes:
      - $PWD/..:/var/lib/ghost/content/themes/weiss-pro
      - ./ghost.db:/var/lib/ghost/content/data/ghost.db
    environment:
      - NODE_ENV=development
    ports:
      - 2368:2368
